{
 "title": "Alex",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Бизнес метрики", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Цена",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 1 },
   "targets": [
    { "expr": "tinkoff_last_price", "legendFormat": "{{figi}}" }
   ]
  },
  {
   "title": "Позиция/Баланс",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tinkoff_position",
     "legendFormat": "position {{account}} {{currency}}"
    },
    { "expr": "tinkoff_balance", "legendFormat": "balance {{account}} {{figi}}" }
   ]
  },
  {
   "title": "Текущие позиции (руб)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tinkoff_position", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Текущий баланс (шт)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tinkoff_balance", "legendFormat": "{{account}} - {{figi}}" }
   ]
  },
  { "title": "Технические метрики", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Время обработки пришедшей свечи",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(bot_step_time_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "quantile99"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(bot_step_time_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "msg_sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(grpc_client_msg_sent_total[$__rate_interval])",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  }
 ]
}